# This workflow will install Python dependencies and run tests with a couple of Python versions
# Github actions documentation: https://docs.github.com/en/actions


name: Demo CI script

on:
  push:
    branches: [ main ]
  # Normally we would trigger the workflow on a PR to the master branch
  # pull_request:
  #   branches: [ main ]

jobs: # A set of actions to be executed
  build:

    runs-on: ubuntu-latest # We can specify which operating systems to run our tests on
    strategy:
      matrix: # `matrix`
        python-version: [3.8, 3.9] # Here you can choose which versions of python to test against

    steps:
    - uses: actions/checkout@v2 # See github.com/actions/checkout (`@v2`specifies version)

    - name: Set up Python ${{ matrix.python-version }} # Note the syntax
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt

    # Make imports prettier
    - name: Make imports pretty
      run: |
        reorder-python-imports main.py

    # Run linting with flake8
    - name: Lint with flake8
      run: |
        python -m flake8

    # Apply type checking
    - name: Run static type checker
      run: python -m mypy

    # Run tests
    - name: Unit testing
      working-directory: ./tests/
      run: pytest
